

POST http://localhost:5210/api/Interest/Calculate
accept: text/plain
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="Yon"

S
--WebAppBoundary
Content-Disposition: form-data; name="Faizlendirme"

1
--WebAppBoundary
Content-Disposition: form-data; name="FaizBirim"

1
--WebAppBoundary
Content-Disposition: form-data; name="FaizYuzde"

5
--WebAppBoundary
Content-Disposition: form-data; name="Anapara"

5
--WebAppBoundary
Content-Disposition: form-data; name="Vade"

5
--WebAppBoundary
Content-Disposition: form-data; name="VadeBirim"

1
--WebAppBoundary--

###

